version: "3"

services:
  connector:
    image: adminbyrequest.azurecr.io/remote-access/connector
    container_name: "connector"
    ports:
      - "8000:80"
    environment:
      - TOKEN__SECRET=9cadd287-37df-4036-a79d-b40bfae310ca
      - TOKEN__PRIVATEKEY=94e54686-5135-4b5b-a003-812fb296797a
      - TOKEN__INITIALIZATIONVECTOR=SUQMTqhjkij19Pm6
      - API__URL=https://connectorapi1.adminbyrequest.com
      - API__KEY=8fb5a261-c594-445e-874a-c1e80a24ba39
      - API__PRIVATEKEY=61d9b279-67d9-4daf-88ad-c8579dcb51f7
      - API__INITIALIZATIONVECTOR=gdOA31OSRYmc#TQL
      - AUTH__TOKEN=736ab57e-b5ec-4e66-88d4-0cbc719ad5c9
    volumes:
      - shared-data:/records
    restart: unless-stopped

  proxy:
    image: adminbyrequest.azurecr.io/remote-access/proxy
    container_name: "proxy"
    environment:
      - CONNECTOR_HOST=connector
      - AUTH__TOKEN=736ab57e-b5ec-4e66-88d4-0cbc719ad5c9
    volumes:
      - shared-data:/records
    depends_on:
      connector:
        condition: service_healthy
    links:
      - connector
    restart: unless-stopped

  discovery:
    image: adminbyrequest.azurecr.io/remote-access/discovery
    container_name: "discovery"
    environment:
      - AUTH__TOKEN=736ab57e-b5ec-4e66-88d4-0cbc719ad5c9
    network_mode: "host"
    depends_on:
      connector:
        condition: service_healthy
    restart: unless-stopped

volumes:
  shared-data:
